# Generated by Django 4.1.3 on 2022-11-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='image',
            field=models.TextField(default='https://joeschmoe.io/api/v1/male/random', max_length=100),
        ),
    ]
